services:
  postgres:
    image: postgres:16
    container_name: fastapi_auction_postgres
    environment:
      POSTGRES_DB: auction_db
      POSTGRES_USER: auction_user
      POSTGRES_PASSWORD: auction_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7
    container_name: fastapi_auction_redis
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      target: builder
    container_name: fastapi_auction_api
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - venv:/app/.venv
      - uv_cache:/root/.cache/uv
    command: >
      bash -c "uv sync --frozen && uv run alembic upgrade head && uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  worker:
    build:
      context: .
      target: builder
    container_name: fastapi_auction_worker
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - venv:/app/.venv
      - uv_cache:/root/.cache/uv
    command: >
      bash -c "uv sync --frozen && uv run celery -A app.core.celery.celery_app worker --loglevel=info"
  
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: fastapi_auction_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
  
  grafana:
    image: grafana/grafana:10.0.3
    container_name: fastapi_auction_grafana
    ports:
      - "3010:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
  redis_data:
  venv:
  uv_cache:
