"""rename_minimun_to_minimum_increment

Revision ID: 95ebab40fba4
Revises: e55c46f7f9f2
Create Date: 2026-05-08 20:48:23.578525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ebab40fba4'
down_revision: Union[str, Sequence[str], None] = 'e55c46f7f9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auction_id', sa.UUID(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('minimum_increment', sa.Float(), nullable=False),
    sa.Column('last_user_id', sa.UUID(), nullable=True),
    sa.Column('last_amount', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('auctions', 'minimun_increment', new_column_name='minimum_increment')
    op.alter_column('auctions_read', 'minimun_increment', new_column_name='minimum_increment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auctions_read', 'minimum_increment', new_column_name='minimun_increment')
    op.alter_column('auctions', 'minimum_increment', new_column_name='minimun_increment')
    op.drop_table('bids_history')
    op.drop_table('bidding')
    # ### end Alembic commands ###
